#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Remember values on the sudoer's account (this script runs on the VPS).
# Also upsert public facts into the deploy user's .env.
ENV_FILE="${ENV_FILE:-$HOME/.xp-website-https.env}"
XP_WEBSITE_HOME="${XP_WEBSITE_HOME:-/home/deploy}"
NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/xp-website}"
DEFAULT_HOSTNAME="xiuqi.dignomor.com"

persist() {
  local key="$1" value="$2" dest="${XP_WEBSITE_HOME}/.env" tmp
  write_env "$key" "$value"
  if [[ -d "$XP_WEBSITE_HOME" ]]; then
    tmp=$(mktemp)
    if sudo test -f "$dest"; then
      sudo grep -vE "^${key}=" "$dest" > "$tmp" || true
    fi
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
    sudo install -o deploy -g deploy -m 600 "$tmp" "$dest"
    rm -f "$tmp"
  fi
}

detect_ipv4() {
  local ip=""
  ip=$(curl -4 -fsS --max-time 3 http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address 2>/dev/null || true)
  if [[ -z "$ip" ]]; then
    ip=$(curl -4 -fsS --max-time 8 https://ifconfig.me/ip 2>/dev/null || true)
  fi
  printf '%s' "$ip"
}

lookup_a() {
  local host="$1"
  if command -v dig >/dev/null 2>&1; then
    dig +short A "$host" @8.8.8.8 | grep -E '^[0-9.]+$' | tail -n1 || true
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import socket,sys; print(socket.gethostbyname(sys.argv[1]))" "$host" 2>/dev/null || true
  else
    getent ahostsv4 "$host" 2>/dev/null | awk '{print $1; exit}' || true
  fi
}

banner "Production HTTPS via Certbot"

# ── 1. Confirm the host ───────────────────────────────────────────────────
stage "Confirm the host"
say "Run this on the Ubuntu VPS as your normal sudoer (not as deploy)."
say "Nginx should already serve production on port 80. Preview stays off the public vhost."
note "Layout root: $XP_WEBSITE_HOME"
if [[ -f /etc/os-release ]]; then
  # shellcheck source=/dev/null
  . /etc/os-release
  note "OS: ${PRETTY_NAME:-unknown}"
fi
if ! sudo -n true 2>/dev/null; then
  say "sudo will prompt for your password when needed."
fi
if systemctl is-active --quiet nginx 2>/dev/null; then
  note "nginx is active"
else
  warn "nginx is not active — start it before issuing a certificate."
fi
if [[ -L "${XP_WEBSITE_HOME}/releases/production/current" ]]; then
  note "production current → $(readlink "${XP_WEBSITE_HOME}/releases/production/current")"
else
  warn "no production current link yet — HTTP-01 still needs a working site on port 80."
fi
if ! confirm "Continue on this host?"; then
  warn "Stopped. SSH into the VPS and re-run there."
  exit 1
fi

# ── 2. Production hostname ────────────────────────────────────────────────
stage "Choose the production hostname"
say "One name only. Apex vs www canonical behavior is deferred."
note "Default: $DEFAULT_HOSTNAME"
ask PRODUCTION_HOSTNAME "Production hostname:"
if [[ -z "$PRODUCTION_HOSTNAME" ]]; then
  PRODUCTION_HOSTNAME="$DEFAULT_HOSTNAME"
fi
if [[ ! "$PRODUCTION_HOSTNAME" =~ ^[A-Za-z0-9.-]+$ ]]; then
  warn "That does not look like a hostname: $PRODUCTION_HOSTNAME"
  exit 1
fi
persist PRODUCTION_HOSTNAME "$PRODUCTION_HOSTNAME"

# ── 3. Public IPv4 ────────────────────────────────────────────────────────
stage "This VPS public IPv4"
say "DNS will point the hostname at this address."
detected_ip="$(detect_ipv4)"
if [[ -n "$detected_ip" && -z "$(_existing VPS_IPV4 || true)" ]]; then
  write_env VPS_IPV4 "$detected_ip"
fi
ask VPS_IPV4 "Public IPv4 of this VPS:"
if [[ ! "$VPS_IPV4" =~ ^[0-9.]+$ ]]; then
  warn "Need a dotted IPv4 address."
  exit 1
fi
persist VPS_IPV4 "$VPS_IPV4"

# ── 4. Point DNS ──────────────────────────────────────────────────────────
stage "Point DNS at this VPS"
say "At whoever holds DNS for this name, create an A record:"
note "  ${PRODUCTION_HOSTNAME}  A  ${VPS_IPV4}"
step "Open that DNS host (registrar or DigitalOcean Networking → Domains if the zone lives there)."
step "Add or edit the A record for this hostname only — do not add www unless you meant to."
step "TTL can stay the provider default."
open_url "https://dns.google/query?name=${PRODUCTION_HOSTNAME}&type=A"
pause "Press Enter after the A record is saved (propagation can take a few minutes)."
while true; do
  resolved="$(lookup_a "$PRODUCTION_HOSTNAME")"
  if [[ "$resolved" == "$VPS_IPV4" ]]; then
    note "Public lookup matches: $resolved"
    break
  fi
  warn "Lookup is '${resolved:-empty}', want $VPS_IPV4"
  pause "Press Enter to check again (Ctrl-C to stop)."
done

# ── 5. Nginx server_name ──────────────────────────────────────────────────
stage "Set Nginx server_name"
say "Certbot's nginx plugin matches a vhost by name. A catch-all '_' will not do."
note "site file: $NGINX_SITE"
if ! confirm "Set server_name to $PRODUCTION_HOSTNAME and reload Nginx?"; then
  SKIPPED+=("Nginx server_name")
else
  if sudo test ! -f "$NGINX_SITE"; then
    sudo tee "$NGINX_SITE" >/dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ${PRODUCTION_HOSTNAME};

    root ${XP_WEBSITE_HOME}/releases/production/current;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
    sudo ln -sfn "$NGINX_SITE" /etc/nginx/sites-enabled/xp-website
    sudo rm -f /etc/nginx/sites-enabled/default
  else
    sudo python3 - "$NGINX_SITE" "$PRODUCTION_HOSTNAME" <<'PY'
import pathlib, re, sys
path, host = pathlib.Path(sys.argv[1]), sys.argv[2]
text = path.read_text()
new, n = re.subn(r"server_name\s+[^;]+;", f"server_name {host};", text)
if n == 0:
    sys.exit("no server_name directive found")
path.write_text(new)
print(f"updated {n} server_name directive(s)")
PY
  fi
  sudo nginx -t
  sudo systemctl reload nginx
  note "Nginx reloaded with server_name $PRODUCTION_HOSTNAME"
fi

# ── 6. Open 80 and 443 ────────────────────────────────────────────────────
stage "Open ports 80 and 443"
say "Let's Encrypt HTTP-01 uses port 80. Visitors need 443 after issuance."
if sudo ufw status 2>/dev/null | grep -qi "Status: active"; then
  note "ufw is active."
  if confirm "Allow the Nginx Full ufw profile (80 + 443)?"; then
    sudo ufw allow 'Nginx Full'
    sudo ufw status numbered | head -n 20 || true
  else
    SKIPPED+=("ufw Nginx Full")
  fi
else
  note "ufw is inactive on this host — leaving it that way (enabling it can lock you out of SSH)."
  step "If a cloud firewall sits in front of this droplet, allow inbound TCP 80 and 443 there."
  pause "Press Enter once 80/443 are reachable from the internet."
fi

# ── 7. Install Certbot ────────────────────────────────────────────────────
stage "Install Certbot"
say "Official install for Nginx on Ubuntu: the Certbot snap (not apt)."
open_url "https://certbot.eff.org/instructions?ws=nginx&os=snap"
step "This stage runs those commands here after you confirm."
if ! confirm "Install or refresh the Certbot snap now?"; then
  SKIPPED+=("Certbot snap install")
else
  if ! command -v snap >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install -y snapd
  fi
  if dpkg -s certbot >/dev/null 2>&1 || dpkg -s python3-certbot-nginx >/dev/null 2>&1; then
    sudo apt-get remove -y certbot python3-certbot-nginx || true
  fi
  sudo snap install --classic certbot
  sudo ln -sfn /snap/bin/certbot /usr/local/bin/certbot
  note "certbot → $(command -v certbot)"
  certbot --version || sudo certbot --version
fi

# ── 8. Issue the certificate ──────────────────────────────────────────────
stage "Issue the Let's Encrypt certificate"
say "Certbot will prove control of the hostname over HTTP, then edit Nginx for HTTPS and redirect."
ask LETSENCRYPT_EMAIL "Email for Let's Encrypt expiry notices:"
if [[ -z "$LETSENCRYPT_EMAIL" || "$LETSENCRYPT_EMAIL" != *@* ]]; then
  warn "Need a real email address for Let's Encrypt notices."
  exit 1
fi
persist LETSENCRYPT_EMAIL "$LETSENCRYPT_EMAIL"
note "sudo certbot --nginx -d $PRODUCTION_HOSTNAME --redirect"
if ! confirm "Issue the certificate and let Certbot edit Nginx?"; then
  SKIPPED+=("certbot --nginx")
else
  sudo certbot --nginx \
    -d "$PRODUCTION_HOSTNAME" \
    --non-interactive \
    --agree-tos \
    --redirect \
    --email "$LETSENCRYPT_EMAIL" \
    --no-eff-email
fi

# ── 9. Verify HTTPS ───────────────────────────────────────────────────────
stage "Verify HTTPS"
say "The production URL should return the Foundation page over TLS."
open_url "https://${PRODUCTION_HOSTNAME}/"
step "In the browser, confirm the lock icon and the sentence “This is my personal website.”"
if curl -fsS --max-time 30 "https://${PRODUCTION_HOSTNAME}/" | grep -q "This is my personal website."; then
  note "curl https://${PRODUCTION_HOSTNAME}/ contains the Foundation text"
else
  warn "curl did not see the Foundation text at https://${PRODUCTION_HOSTNAME}/"
  SKIPPED+=("HTTPS content check")
fi
pause "Press Enter after you have checked the browser."

# ── 10. Renewal dry-run ───────────────────────────────────────────────────
stage "Renewal dry-run"
say "Certbot installs a systemd timer. This dry-run proves renewal config without replacing the live cert."
if confirm "Run sudo certbot renew --dry-run now?"; then
  sudo certbot renew --dry-run
else
  SKIPPED+=("certbot renew --dry-run")
fi

finish
note "Later checks: curl -fsS https://${PRODUCTION_HOSTNAME}/"
note "              sudo certbot renew --dry-run"
