#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

# Remember values on the sudoer's account (this script runs on the VPS).
# Host facts also land in the deploy user's .env (not in git).
ENV_FILE="${ENV_FILE:-$HOME/.xp-website-vps.env}"
DEFAULT_DEPLOY_USER="deploy"
DEFAULT_HOME="/home/deploy"
DEFAULT_GIT_URL="https://github.com/DignoMor/xp-website.git"
NGINX_SITE="${NGINX_SITE:-/etc/nginx/sites-available/xp-website}"

DEPLOY_USER=""
XP_WEBSITE_HOME=""
XP_WEBSITE_REPO_ROOT=""

persist() {
  local key="$1" value="$2" dest tmp
  write_env "$key" "$value"
  dest="${XP_WEBSITE_HOME}/.env"
  if [[ -n "${XP_WEBSITE_HOME:-}" && -d "$XP_WEBSITE_HOME" ]] && id "${DEPLOY_USER:-}" >/dev/null 2>&1; then
    tmp=$(mktemp)
    if sudo test -f "$dest"; then
      sudo grep -vE "^${key}=" "$dest" > "$tmp" || true
    fi
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
    sudo install -o "$DEPLOY_USER" -g "$DEPLOY_USER" -m 600 "$tmp" "$dest"
    rm -f "$tmp"
  fi
}

as_deploy() {
  sudo -u "$DEPLOY_USER" -H -- "$@"
}

detect_ipv4() {
  local ip=""
  ip=$(curl -4 -fsS --max-time 3 http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address 2>/dev/null || true)
  if [[ -z "$ip" ]]; then
    ip=$(curl -4 -fsS --max-time 8 https://ifconfig.me/ip 2>/dev/null || true)
  fi
  printf '%s' "$ip"
}

banner "Provision Ubuntu 24.04 for xp-website"

# ── 1. Confirm the host ───────────────────────────────────────────────────
stage "Confirm the host"
say "Run this on the Ubuntu VPS as your normal sudoer (not as deploy, not on your laptop)."
say "HTTPS and DNS are a later wizard (scripts/provision/https.sh)."
if [[ "$(uname -s)" != Linux ]]; then
  warn "This is not Linux. scp this script to the VPS and run it there with ssh -t."
  exit 1
fi
if [[ "$(id -u)" -eq 0 ]]; then
  warn "You are root. Prefer your sudoer account; sudo will still be used per command."
fi
if [[ -f /etc/os-release ]]; then
  # shellcheck source=/dev/null
  . /etc/os-release
  note "OS: ${PRETTY_NAME:-unknown}"
  if [[ "${VERSION_ID:-}" != "24.04" ]]; then
    warn "This wizard targets Ubuntu 24.04. You are on ${VERSION_ID:-unknown}."
  fi
fi
if ! command -v sudo >/dev/null 2>&1; then
  warn "sudo is required."
  exit 1
fi
if ! sudo -n true 2>/dev/null; then
  say "sudo will prompt for your password when needed."
fi
if ! confirm "Continue on this host?"; then
  warn "Stopped. SSH into the VPS and re-run there."
  exit 1
fi

# ── 2. Choose deploy identity ─────────────────────────────────────────────
stage "Choose deploy identity"
say "These stay on the machine. Do not commit the path into xp-website."
note "Defaults: user $DEFAULT_DEPLOY_USER, home $DEFAULT_HOME"
ask DEPLOY_USER "Deploy username:"
[[ -z "$DEPLOY_USER" ]] && DEPLOY_USER="$DEFAULT_DEPLOY_USER"
if [[ ! "$DEPLOY_USER" =~ ^[a-z_][a-z0-9_-]*$ ]]; then
  warn "That does not look like a Linux username: $DEPLOY_USER"
  exit 1
fi
if [[ "$DEPLOY_USER" == "$(id -un)" ]]; then
  warn "That is this login. The deploy user must be a dedicated account."
  exit 1
fi
ask XP_WEBSITE_HOME "Layout root (deploy home):"
[[ -z "$XP_WEBSITE_HOME" ]] && XP_WEBSITE_HOME="$DEFAULT_HOME"
if [[ "$XP_WEBSITE_HOME" != /* ]]; then
  warn "Need an absolute path."
  exit 1
fi
write_env DEPLOY_USER "$DEPLOY_USER"
write_env XP_WEBSITE_HOME "$XP_WEBSITE_HOME"
note "Will write host facts to $XP_WEBSITE_HOME/.env after the user exists."

# ── 3. Create the deploy user ─────────────────────────────────────────────
stage "Create the deploy user"
say "Login shell, no sudoers, not in the docker group. Linger so rootless Docker survives logout."
if [[ "$XP_WEBSITE_HOME" == /home/* ]]; then
  note "Home is under /home — will set mode 711 so Nginx can traverse without listing (ADR 0001)."
fi
if id "$DEPLOY_USER" >/dev/null 2>&1; then
  note "User $DEPLOY_USER already exists."
  note "groups: $(id -nG "$DEPLOY_USER")"
else
  step "adduser --disabled-password, home $XP_WEBSITE_HOME, shell /bin/bash"
fi
if ! confirm "Create or tighten user $DEPLOY_USER now?"; then
  SKIPPED+=("deploy user $DEPLOY_USER")
else
  if ! id "$DEPLOY_USER" >/dev/null 2>&1; then
    sudo adduser --disabled-password --gecos "xp-website deploy" \
      --home "$XP_WEBSITE_HOME" --shell /bin/bash "$DEPLOY_USER"
  fi
  sudo passwd -l "$DEPLOY_USER" >/dev/null
  if getent group sudo >/dev/null && id -nG "$DEPLOY_USER" | grep -qw sudo; then
    warn "$DEPLOY_USER is in group sudo — not removing automatically. Take them out by hand."
    SKIPPED+=("$DEPLOY_USER still in sudo")
  fi
  if getent group docker >/dev/null && id -nG "$DEPLOY_USER" | grep -qw docker; then
    warn "$DEPLOY_USER is in group docker. Removing them from it."
    sudo gpasswd -d "$DEPLOY_USER" docker || true
  fi
  sudo loginctl enable-linger "$DEPLOY_USER"
  if [[ "$XP_WEBSITE_HOME" == /home/* ]]; then
    sudo chmod 711 "$XP_WEBSITE_HOME"
  fi
  sudo chown "$DEPLOY_USER:$DEPLOY_USER" "$XP_WEBSITE_HOME"
  note "home $(sudo stat -c '%A %U:%G %n' "$XP_WEBSITE_HOME")"
  note "linger $(loginctl show-user "$DEPLOY_USER" -p Linger --value 2>/dev/null || echo unknown)"
fi
persist DEPLOY_USER "$DEPLOY_USER"
persist XP_WEBSITE_HOME "$XP_WEBSITE_HOME"

# ── 4. Install host packages ──────────────────────────────────────────────
stage "Install host packages"
say "Ubuntu packages plus Docker CE from Docker's apt repo. Then disable the rootful daemon."
open_url "https://docs.docker.com/engine/install/ubuntu/"
step "This stage runs those apt commands here after you confirm."
if ! confirm "Install or refresh packages now?"; then
  SKIPPED+=("host packages")
else
  sudo apt-get update
  sudo apt-get install -y ca-certificates curl git nginx uidmap dbus-user-session systemd-container
  # Official Docker apt repo (https://docs.docker.com/engine/install/ubuntu/).
  sudo install -m 0755 -d /etc/apt/keyrings
  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  sudo chmod a+r /etc/apt/keyrings/docker.asc
  sudo tee /etc/apt/sources.list.d/docker.sources >/dev/null <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF
  sudo apt-get update
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
  note "Disabling rootful docker.service / docker.socket — builds must use the deploy user's engine."
  sudo systemctl disable --now docker.service docker.socket 2>/dev/null || true
  sudo rm -f /var/run/docker.sock
  note "dockerd-rootless-setuptool.sh → $(command -v dockerd-rootless-setuptool.sh || echo missing)"
fi

# ── 5. Rootless Docker as deploy ──────────────────────────────────────────
stage "Rootless Docker as deploy"
say "Needs a real logind session so XDG_RUNTIME_DIR is set. sudo su will not do."
open_url "https://docs.docker.com/engine/security/rootless/"
if ! grep -q "^${DEPLOY_USER}:" /etc/subuid || ! grep -q "^${DEPLOY_USER}:" /etc/subgid; then
  warn "$DEPLOY_USER is missing from /etc/subuid or /etc/subgid (need at least 65536 ids)."
  SKIPPED+=("rootless Docker (subuid/subgid)")
elif ! confirm "Install rootless Docker for $DEPLOY_USER now?"; then
  SKIPPED+=("rootless Docker")
else
  note "subuid $(grep "^${DEPLOY_USER}:" /etc/subuid)"
  note "subgid $(grep "^${DEPLOY_USER}:" /etc/subgid)"
  # machinectl is the documented way to get a user session without SSH keys yet.
  sudo machinectl shell "${DEPLOY_USER}@" /bin/bash -lc '
    set -euo pipefail
    echo "whoami=$(whoami) XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-}"
    test -n "${XDG_RUNTIME_DIR:-}"
    dockerd-rootless-setuptool.sh install
    systemctl --user enable docker
    systemctl --user start docker
    docker info
  '
  if sudo machinectl shell "${DEPLOY_USER}@" /bin/bash -lc 'docker info' | grep -qi rootless; then
    note "docker info reports rootless"
  else
    warn "docker info did not mention rootless — check the output above."
    SKIPPED+=("rootless Docker verification")
  fi
fi

# ── 6. Release layout ─────────────────────────────────────────────────────
stage "Release layout"
say "bare.git, releases/{production,preview}, work, logs, lock. Do not add www-data to the deploy group."
if ! confirm "Create the directory tree as $DEPLOY_USER?"; then
  SKIPPED+=("release layout")
else
  as_deploy mkdir -p \
    "$XP_WEBSITE_HOME/bare.git" \
    "$XP_WEBSITE_HOME/releases/production" \
    "$XP_WEBSITE_HOME/releases/preview" \
    "$XP_WEBSITE_HOME/work" \
    "$XP_WEBSITE_HOME/logs" \
    "$XP_WEBSITE_HOME/lock"
  placeholder="$XP_WEBSITE_HOME/releases/production/placeholder"
  if [[ ! -d "$placeholder" ]]; then
    as_deploy mkdir -p "$placeholder"
    printf '%s\n' '<!DOCTYPE html><html><body>This is my personal website.</body></html>' \
      | sudo tee "$placeholder/index.html" >/dev/null
    sudo chown "$DEPLOY_USER:$DEPLOY_USER" "$placeholder/index.html"
  fi
  sudo chmod -R a+rX "$XP_WEBSITE_HOME/releases"
  if [[ ! -e "$XP_WEBSITE_HOME/releases/production/current" ]]; then
    as_deploy ln -sfn "$placeholder" "$XP_WEBSITE_HOME/releases/production/current"
  fi
  note "production current → $(readlink "$XP_WEBSITE_HOME/releases/production/current")"
fi

# ── 7. Hook checkout ──────────────────────────────────────────────────────
stage "Hook checkout"
say "A durable copy of xp-website so post-receive can run scripts/deploy. Visitors never see this tree."
XP_WEBSITE_REPO_ROOT="${XP_WEBSITE_HOME}/src"
ask XP_WEBSITE_GIT_URL "Git clone URL:"
[[ -z "$XP_WEBSITE_GIT_URL" ]] && XP_WEBSITE_GIT_URL="$DEFAULT_GIT_URL"
persist XP_WEBSITE_GIT_URL "$XP_WEBSITE_GIT_URL"
persist XP_WEBSITE_REPO_ROOT "$XP_WEBSITE_REPO_ROOT"
if [[ -f "$XP_WEBSITE_REPO_ROOT/scripts/deploy/post-receive.sh" ]]; then
  note "Already present: $XP_WEBSITE_REPO_ROOT"
elif ! confirm "Clone $XP_WEBSITE_GIT_URL into $XP_WEBSITE_REPO_ROOT?"; then
  SKIPPED+=("hook checkout")
  step "If GitHub is empty or private, rsync the laptop tree to $XP_WEBSITE_REPO_ROOT and chown $DEPLOY_USER."
  pause "Press Enter after scripts/deploy/post-receive.sh exists there."
else
  if ! as_deploy git clone "$XP_WEBSITE_GIT_URL" "$XP_WEBSITE_REPO_ROOT"; then
    warn "Clone failed. Push origin/main, or rsync the laptop tree, then continue."
    step "sudo rm -rf $XP_WEBSITE_REPO_ROOT"
    step "sudo -u $DEPLOY_USER git clone $XP_WEBSITE_GIT_URL $XP_WEBSITE_REPO_ROOT"
    pause "Press Enter after the clone exists."
  fi
fi
if [[ ! -f "$XP_WEBSITE_REPO_ROOT/scripts/deploy/post-receive.sh" ]]; then
  warn "Missing $XP_WEBSITE_REPO_ROOT/scripts/deploy/post-receive.sh"
  SKIPPED+=("XP_WEBSITE_REPO_ROOT scripts")
else
  note "hook scripts are in $XP_WEBSITE_REPO_ROOT/scripts/deploy"
fi

# ── 8. Bare repo + hook ───────────────────────────────────────────────────
stage "Bare repo + hook"
say "Push target for the laptop deploy remote. Wrapper sources .env so Git does not need bashrc."
if ! confirm "Initialize $XP_WEBSITE_HOME/bare.git and install the post-receive wrapper?"; then
  SKIPPED+=("bare repo + hook")
else
  if ! as_deploy git --git-dir="$XP_WEBSITE_HOME/bare.git" rev-parse --is-bare-repository >/dev/null 2>&1; then
    as_deploy git init --bare "$XP_WEBSITE_HOME/bare.git"
  else
    note "bare repo already initialized"
  fi
  hook="$XP_WEBSITE_HOME/bare.git/hooks/post-receive"
  sudo tee "$hook" >/dev/null <<EOF
#!/usr/bin/env bash
set -euo pipefail
# shellcheck disable=SC1091
source ${XP_WEBSITE_HOME}/.env
export XP_WEBSITE_HOME XP_WEBSITE_REPO_ROOT
export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}"
export DOCKER_HOST="\${DOCKER_HOST:-unix://\${XDG_RUNTIME_DIR}/docker.sock}"
exec bash "\${XP_WEBSITE_REPO_ROOT}/scripts/deploy/post-receive.sh"
EOF
  sudo chown "$DEPLOY_USER:$DEPLOY_USER" "$hook"
  sudo chmod 755 "$hook"
  note "bare=$(as_deploy git --git-dir="$XP_WEBSITE_HOME/bare.git" rev-parse --is-bare-repository)"
  note "hook $hook"
fi

# ── 9. SSH key for pushes ─────────────────────────────────────────────────
stage "SSH key for pushes"
say "Your laptop public key goes in ${DEPLOY_USER}'s authorized_keys. The sudoer key is not used."
step "On the laptop: cat ~/.ssh/id_ed25519.pub  (or whichever .pub you actually use)."
step "Paste one line starting with ssh-ed25519 or ssh-rsa — not the private key."
ask DEPLOY_SSH_PUBKEY "Paste the public key line:"
if [[ -z "$DEPLOY_SSH_PUBKEY" ]]; then
  warn "No key pasted."
  SKIPPED+=("authorized_keys")
elif [[ "$DEPLOY_SSH_PUBKEY" != ssh-* && "$DEPLOY_SSH_PUBKEY" != ecdsa-* && "$DEPLOY_SSH_PUBKEY" != sk-* ]]; then
  warn "That does not look like an OpenSSH public key."
  SKIPPED+=("authorized_keys")
else
  as_deploy mkdir -p "$XP_WEBSITE_HOME/.ssh"
  sudo chmod 700 "$XP_WEBSITE_HOME/.ssh"
  auth="$XP_WEBSITE_HOME/.ssh/authorized_keys"
  if sudo test -f "$auth" && sudo grep -Fqx "$DEPLOY_SSH_PUBKEY" "$auth"; then
    note "Key already in authorized_keys"
  else
    printf '%s\n' "$DEPLOY_SSH_PUBKEY" | sudo tee -a "$auth" >/dev/null
  fi
  sudo chown -R "$DEPLOY_USER:$DEPLOY_USER" "$XP_WEBSITE_HOME/.ssh"
  sudo chmod 600 "$auth"
  note "authorized_keys updated"
fi
detected_ip="$(detect_ipv4)"
ask DEPLOY_SSH_HOST "Host you will SSH to as $DEPLOY_USER (IP, DNS, or laptop ssh alias):"
if [[ -z "$DEPLOY_SSH_HOST" && -n "$detected_ip" ]]; then
  DEPLOY_SSH_HOST="$detected_ip"
fi
DEPLOY_REMOTE="${DEPLOY_USER}@${DEPLOY_SSH_HOST}:${XP_WEBSITE_HOME}/bare.git"
if [[ -n "${DEPLOY_SSH_HOST:-}" ]]; then
  persist DEPLOY_SSH_HOST "$DEPLOY_SSH_HOST"
  persist DEPLOY_REMOTE "$DEPLOY_REMOTE"
fi
say "Lock password SSH for $DEPLOY_USER only. Your sudoer account is unchanged."
if confirm "Write Match User $DEPLOY_USER PasswordAuthentication no and reload ssh?"; then
  dropin="/etc/ssh/sshd_config.d/50-xp-website-deploy.conf"
  sudo tee "$dropin" >/dev/null <<EOF
Match User ${DEPLOY_USER}
    PasswordAuthentication no
    KbdInteractiveAuthentication no
EOF
  if sudo sshd -t; then
    sudo systemctl reload ssh
    note "reloaded ssh with $dropin"
  else
    warn "sshd -t failed — not reloading. Inspect $dropin"
    SKIPPED+=("sshd Match User")
  fi
else
  SKIPPED+=("sshd Match User")
fi
step "On the laptop, test: ssh ${DEPLOY_USER}@${DEPLOY_SSH_HOST:-YOUR_VPS} whoami"
pause "Press Enter after that prints ${DEPLOY_USER} with no password prompt."

# ── 10. Nginx, production only ────────────────────────────────────────────
stage "Nginx, production only"
say "Native Nginx serves releases/production/current on port 80. No reverse proxy, no Node."
say "server_name stays _ until the HTTPS wizard sets the hostname."
note "site file: $NGINX_SITE"
if ! confirm "Install or refresh the HTTP vhost and reload Nginx?"; then
  SKIPPED+=("Nginx site")
else
  if sudo test -f "$NGINX_SITE" && sudo grep -q ssl_certificate "$NGINX_SITE"; then
    note "Existing site has TLS — leaving it (https.sh owns that file)."
  else
    sudo tee "$NGINX_SITE" >/dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root ${XP_WEBSITE_HOME}/releases/production/current;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
    sudo ln -sfn "$NGINX_SITE" /etc/nginx/sites-enabled/xp-website
    sudo rm -f /etc/nginx/sites-enabled/default
  fi
  sudo nginx -t
  sudo systemctl enable --now nginx
  sudo systemctl reload nginx
  if curl -fsS --max-time 10 http://127.0.0.1/ | grep -q "This is my personal website."; then
    note "curl http://127.0.0.1/ contains the Foundation text"
  else
    warn "curl did not see the Foundation text — check home 711 and a+rX on releases."
    SKIPPED+=("HTTP content check")
  fi
fi

# ── 11. Sanity check ──────────────────────────────────────────────────────
stage "Sanity check"
say "On the laptop, in xp-website, add the deploy remote (GitHub origin stays as it is)."
note "git remote add deploy ${DEPLOY_REMOTE:-${DEPLOY_USER}@YOUR_VPS:${XP_WEBSITE_HOME}/bare.git}"
note "git ls-remote deploy"
note "git push deploy main"
say "First push builds on the VPS. Then: tail $XP_WEBSITE_HOME/logs/deploy.log"
pause "Press Enter to finish."

finish
note "Later: bash scripts/provision/https.sh  (issue #10)"
note "Do not add www-data to group $DEPLOY_USER."
# ──────────────────────────────────────────────────────────────────────────
